#!/usr/bin/env python

import argparse
import json
import logging
import os
import signal
import ssl
import sys
import paho.mqtt.client as mqtt

from cachetools import TTLCache
from jsonpath import pointer, exceptions


verify_mode = {
    'CERT_NONE': ssl.CERT_NONE,
    'CERT_OPTIONAL': ssl.CERT_OPTIONAL,
    'CERT_REQUIRED': ssl.CERT_REQUIRED
}

tls_versions = {
    'TLSv1': ssl.PROTOCOL_TLSv1,
    'TLSv1.1': ssl.PROTOCOL_TLSv1_1,
    'TLSv1.2': ssl.PROTOCOL_TLSv1_2
}


mqtt_client = None
daemon_args = None
topic_states = {}
publish_cache = TTLCache(maxsize=4096, ttl=600)
receive_cache = TTLCache(maxsize=4096, ttl=600)


def eprint(*args, **kwargs):
    print(*args, file=sys.stderr, **kwargs)


def format_payload(target, value):
    config = daemon_args.mqtt_targets[target]

    if 'factor' in config:
        value = float(value) * config['factor']
    if 'round' in config:
        value = round(float(value), config['round'])
    if 'type' in config:
        if config['type'] == 'int':
            value = int(float(value))
        elif config['type'] == 'float':
            value = float(value)
        elif config['type'] == 'str':
            value = str(value)
        elif config['type'] == 'bool_int':
            value = int(str(value).lower() in ['true', '1', 'on', 'yes'])
        elif config['type'] == 'bool':
            value = str(bool(str(value).lower() in ['true', '1', 'on', 'yes'])).lower()

    return value


def handle(source, value):
    logging.debug('Processing message "%s" from topic "%s"', value, source)

    target_topics = daemon_args.mqtt_sources[source]

    for target in target_topics:
        if daemon_args.mqtt_targets[target]['handle'] == 'publish':
            handle_publish(target, source, value)
        elif daemon_args.mqtt_targets[target]['handle'] == 'split':
            handle_split(target, source, value)
        elif daemon_args.mqtt_targets[target]['handle'] == 'combine':
            handle_combine(target, source, value)
        elif daemon_args.mqtt_targets[target]['handle'] == 'add':
            handle_add(target, source, value)
        elif daemon_args.mqtt_targets[target]['handle'] == 'min':
            handle_min(target, source, value)
        elif daemon_args.mqtt_targets[target]['handle'] == 'max':
            handle_max(target, source, value)
        elif daemon_args.mqtt_targets[target]['handle'] == 'json':
            handle_json(target, source, value)



def handle_publish(target, source, value):
    logging.debug('Publish incoming message from topic %s with value %s to %s', source, value, target)

    publish(target, format_payload(target, value))


def handle_combine(target, source, value):
    logging.debug('Combine incoming messages for topic "%s" with value "%s" from "%s"', target, value, source)

    setstate(target, source, str(value))

    values = states(target, break_if_missing=True)

    if values is None:
        logging.info('Missing values in cache for target "%s"', target)
        return

    if 'append' in daemon_args.mqtt_targets[target]:
        values = values + daemon_args.mqtt_targets[target]['append']

    value = ' '.join(map(str, values))

    publish(target, value)


def handle_add(target, source, value):
    logging.debug('Adding incoming messages for topic "%s" with value "%s" from "%s"', target, value, source)

    setstate(target, source, float(value))

    values = states(target, break_if_missing=True)

    if values is None:
        logging.info('Missing values in cache for target "%s"', target)
        return

    publish(target, format_payload(target, sum(values)))


def handle_min(target, source, value):
    logging.debug('Determine minimum for topic "%s"', target)

    setstate(target, source, float(value))

    values = states(target)

    if len(values) == 0:
        logging.info('No values in cache for target "%s"', target)
        return

    publish(target, format_payload(target, min(values)))


def handle_max(target, source, value):
    logging.debug('Determine maximum for topic "%s"', target)

    setstate(target, source, float(value))

    values = states(target)

    if len(values) == 0:
        logging.info('No values in target cache for %s', target)
        return

    publish(target,format_payload(target, max(values)))


def handle_split(target, source, value):
    logging.debug('Split incoming message from topic %s with value %s for %s', source, value, target)

    setstate(target, source, str(value))

    if 'select' not in daemon_args.mqtt_targets[target]:
        logging.error('Cannot split as no select is specified for topic %s', target)
        return

# TODO: create topics automatically as subtopics if 'select' is not defined
    select = daemon_args.mqtt_targets[target]['select']
    values = value.split(' ')

    publish(target, format_payload(target, values[select]))


def handle_json(target, source, value):
    logging.debug('Parse incoming JSON message from topic %s with value %s for %s', source, value, target)

    setstate(target, source, str(value))

    if 'query' not in daemon_args.mqtt_targets[target]:
        logging.error('No query is specified for topic %s', target)
        return

    try:
        jsonvalue = json.loads(value)
    except json.decoder.JSONDecodeError:
        logging.error('Parsing error for message %s', value)
        return

    query = daemon_args.mqtt_targets[target]['query']
    try:
        jqresult = pointer.resolve(query, jsonvalue)
        publish(target, format_payload(target, jqresult))
    except exceptions.JSONPointerKeyError:
        logging.error('Query error for message %s', value)


def publish(topic, payload):
    logging.info('Publish value "%s" to topic "%s"', topic, payload)

    if topic in publish_cache.keys():
        logging.debug('Cache hit for topic "%s"', topic)
        if receive_cache.get(topic) == payload:
            logging.info('No change in value, message "%s" for topic "%s" not published', payload, topic)
            return

    publish_cache[topic] = payload
    mqtt_client.publish(topic, payload)


def setstate(target, source, value):
    if topic_states[target] is None:
        topic_states[target] = {}

    topic_states[target][source] = value


def states(target, break_if_missing=False):
    values = []
    for s in daemon_args.mqtt_targets[target]['sources']:
        if s not in topic_states[target]:
            logging.info('No value for source topic "%s" in cache for target "%s"', s, target)
            if break_if_missing:
                return
            else:
                continue
        values.append(topic_states[target][s])
    return values


def on_mqtt_connect(client, userdata, flags, reason_code, properties):
    for topic in daemon_args.mqtt_sources.keys():
        logging.info('Subscribed to topic "%s"', topic)
        client.subscribe(topic)


def on_mqtt_received(client, userdata, message):
    logging.debug('Received message "%s" for topic "%s"', message.payload, message.topic)

    if message.topic in receive_cache.keys():
        logging.debug('Cache hit for topic "%s"', message.topic)
        if receive_cache.get(message.topic) == message.payload:
            logging.info('Received message "%s" for topic "%s", but no change in value', message.payload, message.topic)
            return

    receive_cache[message.topic] = message.payload

    topic = message.topic
    value = str(message.payload.decode())

    handle(topic, value)


def init_mqtt():
    logging.debug('Starting MQTT')
    global daemon_args
    mqtt_client = mqtt.Client(mqtt.CallbackAPIVersion.VERSION2, daemon_args.mqtt_clientid)
    if daemon_args.mqtt_tls:
        cert_reqs = verify_mode[daemon_args.mqtt_verify_mode] if daemon_args.mqtt_verify_mode in verify_mode else None
        tls_version = tls_versions[daemon_args.mqtt_tls_version] if daemon_args.mqtt_tls_version in tls_versions else None
        ca_certs = daemon_args.mqtt_ssl_ca_path if daemon_args.mqtt_ssl_ca_path else None
        mqtt_client.tls_set(ca_certs=ca_certs, cert_reqs=cert_reqs, tls_version=tls_version)
        mqtt_client.tls_insecure_set(daemon_args.mqtt_tls_no_verify)
    if daemon_args.verbose:
        logging.basicConfig(level=logging.DEBUG)
        mqtt_client.enable_logger()
    if daemon_args.mqtt_user is not None and daemon_args.mqtt_password is not None:
        mqtt_client.username_pw_set(daemon_args.mqtt_user, daemon_args.mqtt_password)
    mqtt_client.on_connect = on_mqtt_connect
    mqtt_client.on_message = on_mqtt_received
    mqtt_client.connect(daemon_args.mqtt_host, daemon_args.mqtt_port, daemon_args.mqtt_keepalive)
    return mqtt_client


def parse_args():
    parser = argparse.ArgumentParser(
            prog='mqttbroker',
            description='An MQTT broker daemon',
            epilog='Have a lot of fun!')
    parser.add_argument('-m', '--mqtt_host', type=str,
            default='localhost',
            help='The hostname of the MQTT server. Default is localhost')
    parser.add_argument('--mqtt_port', type=int,
            default=1883,
            help='The port of the MQTT server. Default is 1883')
    parser.add_argument('--mqtt_keepalive', type=int,
            default=30,
            help='The keep alive interval for the MQTT server connection in seconds. Default is 30')
    parser.add_argument('--mqtt_clientid', type=str,
            default='mqttbroker',
            help='The clientid to send to the MQTT server. Default is mqttbroker')
    parser.add_argument('-u', '--mqtt_user', type=str,
            help='The username for the MQTT server connection.')
    parser.add_argument('-p', '--mqtt_password', type=str,
            help='The password for the MQTT server connection.')
    parser.add_argument('--mqtt_tls',
            default=False,
            action='store_true',
            help='Use SSL/TLS encryption for MQTT connection.')
    parser.add_argument('--mqtt_tls_version', type=str,
            default='TLSv1.2',
            help='The TLS version to use for MQTT. One of TLSv1, TLSv1.1, TLSv1.2. Default is TLSv1.2')
    parser.add_argument('--mqtt_verify_mode', type=str,
            default='CERT_REQUIRED',
            help='The SSL certificate verification mode. One of CERT_NONE, CERT_OPTIONAL, CERT_REQUIRED. Default is CERT_REQUIRED')
    parser.add_argument('--mqtt_ssl_ca_path', type=str,
            help='The SSL certificate authority file to verify the MQTT server.')
    parser.add_argument('--mqtt_tls_no_verify',
            default=False,
            action='store_true',
            help='Do not verify SSL/TLS constraints like hostname.')
    parser.add_argument('-c', '--config', type=str,
            default='/etc/mqttbroker.conf',
            help='The path to the config file. Default is /etc/mqttbroker.conf')
    parser.add_argument('-v', '--verbose',
            default=False,
            action='store_true',
            help='Be verbose while running.')
    args = parser.parse_args()

    if args.verbose:
        logging.basicConfig(level=logging.DEBUG)

    return args


def parse_config():
    logging.debug('Parse config')
    global daemon_args

    daemon_args.topics = []

    if not os.path.isfile(daemon_args.config):
        logging.warning('Config file not found: %s', daemon_args.config)
        return

    with open(daemon_args.config, "r") as config_file:
        data = json.load(config_file)
        if 'mqtt_host' in data:
            daemon_args.mqtt_host = data['mqtt_host']
        if 'mqtt_port' in data:
            daemon_args.mqtt_port = int(data['mqtt_port'])
        if 'mqtt_keepalive' in data:
            daemon_args.mqtt_keepalive = int(data['mqtt_keepalive'])
        if 'mqtt_clientid' in data:
            daemon_args.mqtt_clientid = data['mqtt_clientid']
        if 'mqtt_user' in data:
            daemon_args.mqtt_user = data['mqtt_user']
        if 'mqtt_password' in data:
            daemon_args.mqtt_password = data['mqtt_password']
        if 'mqtt_tls' in data:
            daemon_args.mqtt_tls = data['mqtt_tls'].lower() == 'true'
        if 'mqtt_tls_version' in data:
            daemon_args.mqtt_tls_version = data['mqtt_tls_version']
        if 'mqtt_verify_mode' in data:
            daemon_args.mqtt_verify_mode = data['mqtt_verify_mode']
        if 'mqtt_ssl_ca_path' in data:
            daemon_args.mqtt_ssl_ca_path = data['mqtt_ssl_ca_path']
        if 'mqtt_tls_no_verify' in data:
            daemon_args.mqtt_tls_no_verify = data['mqtt_tls_no_verify'].lower() == 'true'
        if 'verbose' in data:
            daemon_args.verbose = data['verbose'].lower() == 'true'
        if 'topics' in data:
            daemon_args.topics = data['topics']


def init_topics():
    logging.debug('Init topics')
    global topic_states

    daemon_args.mqtt_sources = {}
    daemon_args.mqtt_targets = {}

    for target in daemon_args.topics:
        daemon_args.mqtt_targets[target['topic']] = {}

        daemon_args.mqtt_targets[target['topic']]['handle'] = target['handle'] if 'handle' in target else 'publish'
        daemon_args.mqtt_targets[target['topic']]['type'] = target['type'] if 'type' in target else 'str'

        daemon_args.mqtt_targets[target['topic']]['sources'] = []

        if 'append' in target:
            daemon_args.mqtt_targets[target['topic']]['append'] = target['append']
        if 'select' in target:
            daemon_args.mqtt_targets[target['topic']]['select'] = int(target['select'])
        if 'round' in target:
            daemon_args.mqtt_targets[target['topic']]['round'] = int(target['round'])
        if 'factor' in target:
            daemon_args.mqtt_targets[target['topic']]['factor'] = float(target['factor'])
        if 'query' in target:
            daemon_args.mqtt_targets[target['topic']]['query'] = target['query']

        for source in target['sources']:
            if source in daemon_args.mqtt_sources:
                daemon_args.mqtt_sources[source].append( target['topic'] )
            else:
                daemon_args.mqtt_sources[source] = [ target['topic'] ]

            daemon_args.mqtt_targets[target['topic']]['sources'].append( source )

        topic_states[target['topic']] = {}

        if 'init' in target:
            for source in daemon_args.mqtt_targets[target['topic']]['sources']:
                topic_states[target['topic']][source] = format_payload(target['topic'], target['init'])


def shutdown(signum, frame):
    global mqtt_client
    logging.info('Shutdown...')
    if mqtt_client is not None:
        logging.info('Stopping MQTT')
        mqtt_client.loop_stop()
        mqtt_client.disconnect()
    logging.info('Bye!')
    exit(0)


def main():
    global daemon_args, mqtt_client

    signal.signal(signal.SIGINT, shutdown)
    signal.signal(signal.SIGTERM, shutdown)

    # Configuration
    daemon_args = parse_args()
    parse_config()
    init_topics()

    # Verbosity
    if daemon_args.verbose:
        logging.basicConfig(level=logging.DEBUG)

    # MQTT connection
    mqtt_client = init_mqtt()
    mqtt_client.loop_forever()


if __name__ == "__main__":
    main()
