#!/usr/bin/env python

import argparse
import json
import logging
import os
import ssl
import sys
import paho.mqtt.client as mqtt

from cachetools import TTLCache

mqtt_client = None
daemon_args = None
topic_states = {}
publish_cache = TTLCache(maxsize=1024, ttl=600)
receive_cache = TTLCache(maxsize=1024, ttl=600)


def eprint(*args, **kwargs):
    print(*args, file=sys.stderr, **kwargs)


def format_payload(target, value):
    config = daemon_args.mqtt_targets[target]

    if 'factor' in config:
        value = float(value) * config['factor']
    if 'round' in config:
        value = round(float(value), config['round'])
    if 'type' in config:
        if config['type'] == 'int':
            value = int(float(value))
        elif config['type'] == 'float':
            value = float(value)
        elif config['type'] == 'str':
            value = str(value)
        elif config['type'] == 'bool':
            value = bool(value)

    return value


def handle(source, value):
    logging.debug('Processing message "%s" from topic "%s"', value, source)

    target_topics = daemon_args.mqtt_sources[source]

    for target in target_topics:
        if daemon_args.mqtt_targets[target]['handle'] == 'publish':
            handle_publish(target, source, value)
        elif daemon_args.mqtt_targets[target]['handle'] == 'split':
            handle_split(target, source, value)
        elif daemon_args.mqtt_targets[target]['handle'] == 'combine':
            handle_combine(target, source, value)
        elif daemon_args.mqtt_targets[target]['handle'] == 'add':
            handle_add(target, source, value)
        elif daemon_args.mqtt_targets[target]['handle'] == 'min':
            handle_min(target, source, value)
        elif daemon_args.mqtt_targets[target]['handle'] == 'max':
            handle_max(target, source, value)


def handle_publish(target, source, value):
    logging.debug('Publish incoming message from topic %s with value %s to %s', source, value, target)

    publish(target, value)


def handle_combine(target, source, value):
    logging.debug('Combine incoming messages for topic "%s" with value "%s" from "%s"', target, value, source)

    setstate(target, source, str(value))

    values = states(target, break_if_missing=True)

    if values is None:
        logging.info('Missing values in cache for target "%s"', target)
        return

    if 'append' in daemon_args.mqtt_targets[target]:
        values = values + daemon_args.mqtt_targets[target]['append']

    value = ' '.join(map(str, values))

    publish(target, value)


def handle_add(target, source, value):
    logging.debug('Adding incoming messages for topic "%s" with value "%s" from "%s"', target, value, source)

    setstate(target, source, float(value))

    values = states(target, break_if_missing=True)

    if values is None:
        logging.info('Missing values in cache for target "%s"', target)
        return

    publish(target, sum(values))


def handle_min(target, source, value):
    logging.debug('Determine minimum for topic "%s"', target)

    setstate(target, source, float(value))

    values = states(target)

    if len(values) == 0:
        logging.info('No values in cache for target "%s"', target)
        return

    publish(target, min(values))


def handle_max(target, source, value):
    logging.debug('Determine maximum for topic "%s"', target)

    setstate(target, source, float(value))

    values = states(target)

    if len(values) == 0:
        logging.info('No values in target cache for %s', target)
        return

    publish(target, max(values))


def handle_split(target, source, value):
    logging.debug('Split incoming message from topic %s with value %s for %s', source, value, target)

    setstate(target, source, str(value))

    if 'select' not in daemon_args.mqtt_targets[target]:
        logging.error('Cannot split as no select is specified for topic %s', target)
        return

    select = daemon_args.mqtt_targets[target]['select']
    values = value.split(' ')

    publish(target, values[select])


def publish(topic, value):
    payload = format_payload(topic, value)
    logging.info('Publish value "%s" to topic "%s"', topic, payload)

    if topic in publish_cache.keys():
        logging.debug('Cache hit for topic "%s"', topic)
        if receive_cache.get(topic) == payload:
            logging.info('No change in value, message "%s" for topic "%s" not published', payload, topic)
            return

    publish_cache[topic] = payload
    mqtt_client.publish(topic, payload)


def setstate(target, source, value):
    if topic_states[target] is None:
        topic_states[target] = {}

    topic_states[target][source] = value


def states(target, break_if_missing=False):
    values = []
    for s in daemon_args.mqtt_targets[target]['sources']:
        if s not in topic_states[target]:
            logging.info('No value for source topic "%s" in cache for target "%s"', s, target)
            if break_if_missing:
                return
            else:
                continue
        values.append(topic_states[target][s])
    return values


def on_mqtt_connect(client, userdata, flags, rc):
    for topic in daemon_args.mqtt_sources.keys():
        logging.info('Subscribed to topic "%s"', topic)
        client.subscribe(topic)


def on_mqtt_received(client, userdata, message):
    logging.debug('Received message "%s" for topic "%s"', message.payload, message.topic)

    if message.topic in receive_cache.keys():
        logging.debug('Cache hit for topic "%s"', message.topic)
        if receive_cache.get(message.topic) == message.payload:
            logging.info('Received message "%s" for topic "%s", but no change in value', message.payload, message.topic)
            return

    receive_cache[message.topic] = message.payload

    topic = message.topic
    value = str(message.payload.decode())

    handle(topic, value)


def start_mqtt():
    logging.debug('Starting MQTT')
    global daemon_args, mqtt_client
    mqtt_client = mqtt.Client(daemon_args.mqtt_clientid)
    if 'mqtt_ssl_ca_path' in daemon_args:
        mqtt_client.tls_set(daemon_args.mqtt_ssl_ca_path, tls_version=ssl.PROTOCOL_TLSv1_2)
    if daemon_args.verbose:
        mqtt_client.enable_logger()
    if daemon_args.mqtt_user is not None and daemon_args.mqtt_password is not None:
        mqtt_client.username_pw_set(daemon_args.mqtt_user, daemon_args.mqtt_password)
    mqtt_client.on_connect = on_mqtt_connect
    mqtt_client.on_message = on_mqtt_received
    mqtt_client.connect(daemon_args.mqtt_host, daemon_args.mqtt_port, daemon_args.mqtt_keepalive)
    mqtt_client.loop_forever()


def parse_args():
    global daemon_args
    parser = argparse.ArgumentParser(
            prog='mqttbroker',
            description='An MQTT broker daemon',
            epilog='Have a lot of fun!')
    parser.add_argument('-m', '--mqtt_host', type=str,
            default='localhost',
            help='The hostname of the MQTT server. Default is localhost')
    parser.add_argument('--mqtt_port', type=int,
            default=1883,
            help='The port of the MQTT server. Default is 1883')
    parser.add_argument('--mqtt_keepalive', type=int,
            default=30,
            help='The keep alive interval for the MQTT server connection in seconds. Default is 30')
    parser.add_argument('--mqtt_clientid', type=str,
            default='mqttbroker',
            help='The clientid to send to the MQTT server. Default is mqttbroker')
    parser.add_argument('-u', '--mqtt_user', type=str,
            help='The username for the MQTT server connection.')
    parser.add_argument('-p', '--mqtt_password', type=str,
            help='The password for the MQTT server connection.')
    parser.add_argument('-c', '--config', type=str,
            default='/etc/mqttbroker.conf',
            help='The path to the config file. Default is /etc/mqttbroker.conf')
    parser.add_argument('-v', '--verbose',
            default=False,
            action='store_true',
            help='Be verbose while running.')
    daemon_args = parser.parse_args()


def parse_config():
    logging.debug('Parse config')

    daemon_args.items = []

    if not os.path.isfile(daemon_args.config):
        logging.warning('Config file not found: %s', daemon_args.config)
        return

    with open(daemon_args.config, "r") as config_file:
        data = json.load(config_file)
        if 'mqtt_host' in data:
            daemon_args.mqtt_host = data['mqtt_host']
        if 'mqtt_port' in data:
            daemon_args.mqtt_port = int(data['mqtt_port'])
        if 'mqtt_keepalive' in data:
            daemon_args.mqtt_keepalive = int(data['mqtt_keepalive'])
        if 'mqtt_clientid' in data:
            daemon_args.mqtt_clientid = data['mqtt_clientid']
        if 'mqtt_user' in data:
            daemon_args.mqtt_user = data['mqtt_user']
        if 'mqtt_password' in data:
            daemon_args.mqtt_password = data['mqtt_password']
        if 'mqtt_ssl_ca_path' in data:
            daemon_args.mqtt_ssl_ca_path = data['mqtt_ssl_ca_path']
        if 'topics' in data:
            daemon_args.topics = data['topics']


def init_topics():
    logging.debug('Init topics')
    global topic_states

    daemon_args.mqtt_sources = {}
    daemon_args.mqtt_targets = {}

    for target in daemon_args.topics:
        daemon_args.mqtt_targets[target['topic']] = {}

        daemon_args.mqtt_targets[target['topic']]['handle'] = target['handle'] if 'handle' in target else 'publish'
        daemon_args.mqtt_targets[target['topic']]['type'] = target['type'] if 'type' in target else 'str'

        daemon_args.mqtt_targets[target['topic']]['sources'] = []

        if 'append' in target:
            daemon_args.mqtt_targets[target['topic']]['append'] = target['append']
        if 'select' in target:
            daemon_args.mqtt_targets[target['topic']]['select'] = int(target['select'])
        if 'round' in target:
            daemon_args.mqtt_targets[target['topic']]['round'] = int(target['round'])
        if 'factor' in target:
            daemon_args.mqtt_targets[target['topic']]['factor'] = float(target['factor'])

        for source in target['sources']:
            if source in daemon_args.mqtt_sources:
                daemon_args.mqtt_sources[source].append( target['topic'] )
            else:
                daemon_args.mqtt_sources[source] = [ target['topic'] ]

            daemon_args.mqtt_targets[target['topic']]['sources'].append( source )

    topic_states = dict.fromkeys(daemon_args.mqtt_targets)


def main():
    logging.basicConfig(level=logging.DEBUG)
    parse_args()
    parse_config()
    init_topics()
    start_mqtt()


if __name__ == "__main__":
    main()
